1 explicit pages:
  config/english/config_en.prc

2 implicit pages:
  /c/Panda3D-1.8.1/etc/Config.prc
  /c/Panda3D-1.8.1/etc/Confauto.prc

serverVersion:  sv-1.0.0
PAccount: accountServer from launcher:  
PAccount: default accountServer:  https://pirates.go.com
Initializing quest ladders...
:MagicWordManager(warning): You risk being banned if you abuse this mate!
:MagicWordManager(warning): I will have Jack cut you into pieces! (a.k.a. banned forever)
:DistributedObjectGlobal(warning): ChatManager going online
:DistributedShipLoader(warning): ShipLoader going online
########## startReaderPollTask Pirate
########## stopReaderPollTask Pirate
########## startReaderPollTask Pirate
########## stopReaderPollTask Pirate
New DO:401000001, dclass:PiratesDistrict
New DO:401000002, dclass:DistributedPopulationTracker
getSubTimeList
 sub was None for 0
setEnvironment unnamed 8 {}
getSubTimeList
 sub was None for 8
Exception occurred while processing Func-toggleUpState-11 of Sequence-17:
Sequence-17:
  0.000 Sequence-17 {
  0.000   *Func-cancelIval-10
  0.000   *Func-toggleUpState-11
  0.000   Parallel-16 {
  0.000     LerpHprInterval-12: hpr to 0 0 -180 dur 0.5
  0.000     LerpPosInterval-13: pos to 0.415 0 0.6 dur 0.5
  0.500   }
  0.500 }

Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\direct\showbase\ShowBase.py", line 1791, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.8.1\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.8.1\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "pirates\piratesgui\ShardPanel.py", line 123, in toggleUpState
    self.syncShardList()
  File "pirates\piratesgui\ShardPanel.py", line 173, in syncShardList
    active = set(shard[0])
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\direct\distributed\ConnectionRepository.py", line 610, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.8.1\direct\distributed\ConnectionRepository.py", line 615, in readerPollOnce
    if self.checkDatagram():
  File "C:\Panda3D-1.8.1\direct\showbase\ShowBase.py", line 1791, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.8.1\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.8.1\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "pirates\piratesgui\ShardPanel.py", line 123, in toggleUpState
    self.syncShardList()
  File "pirates\piratesgui\ShardPanel.py", line 173, in syncShardList
    active = set(shard[0])
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Tyler\Desktop\POTCOR-src\pirates\piratesbase\PiratesStart.py", line 79, in <module>
    run()
  File "C:\Panda3D-1.8.1\direct\showbase\ShowBase.py", line 2921, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.8.1\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Panda3D-1.8.1\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Panda3D-1.8.1\direct\distributed\ConnectionRepository.py", line 610, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Panda3D-1.8.1\direct\distributed\ConnectionRepository.py", line 615, in readerPollOnce
    if self.checkDatagram():
  File "C:\Panda3D-1.8.1\direct\showbase\ShowBase.py", line 1791, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.8.1\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.8.1\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.8.1\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "pirates\piratesgui\ShardPanel.py", line 123, in toggleUpState
    self.syncShardList()
  File "pirates\piratesgui\ShardPanel.py", line 173, in syncShardList
    active = set(shard[0])
TypeError: 'int' object is not iterable
